# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "feature/build-with-bazel"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - uses: bazel-contrib/setup-bazel@0.8.5
#      with:
#        # Avoid downloading Bazel every time.
#        bazelisk-cache: true
#        # Store build cache per workflow.
#        disk-cache: ${{ github.workflow }}
#        # Share repository cache between workflows.
#        repository-cache: true

    - name: Build
      run: ./build.sh
      #run: go get && go build

    - name: Upload the artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prometheus-exporter-logged-users
        path: prometheus-exporter-logged-users
